// Builds the single JS asset the RCL ships (Frontend-Architecture.md §4: "the only npm
// surface in the product"). Output lands in Castmill.UI/wwwroot/js and is gitignored —
// it is build output, regenerated by `npm run build` and by the RCL's BuildEditorInterop
// target. Phase F4 replaces the stub source with the TipTap bundle; the budget it has to
// meet then is < 250 KB gzip (G2 / story 5.1).

import { build, context } from 'esbuild';
import { fileURLToPath } from 'node:url';

const outfile = fileURLToPath(new URL('../Castmill.UI/wwwroot/js/castmill-editor.js', import.meta.url));

/** @type {import('esbuild').BuildOptions} */
const options = {
    entryPoints: [fileURLToPath(new URL('src/index.js', import.meta.url))],
    outfile,
    bundle: true,
    format: 'esm',
    target: 'es2022',
    platform: 'browser',
    sourcemap: true,
    minify: true,
    legalComments: 'linked',
    logLevel: 'info',
};

if (process.argv.includes('--watch')) {
    const ctx = await context(options);
    await ctx.watch();
    console.log('watching editor-interop…');
} else {
    await build(options);
}
